version: '3'
services:
  helium_packet_router:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/team-helium/hpr:local
    container_name: helium_packet_router
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "/var/data:/var/data"
  localstack:
    image: localstack/localstack:latest
    restart: always
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./test/scripts:/docker-entrypoint-initaws.d"
      