server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: XXXX

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      server: helium_packet_router-local
      __path__: /var/log/XXX.log