#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           helium-packet-router
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Intermediary for LoRaWAN Network Server (LNS)
# Description:
#  Helium packet router (hpr) is an open-source project
#  conforming to LoRaWAN 1.0.x specification.
#  See https://github.com/helium/helium-packet-router
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

BASE=helium-packet-router

# Modify these in /etc/default/$BASE (/etc/default/helium-packet-router)
# FIXME: $DAEMON conflates launcher script with executable of the running process.
DAEMON=/opt/hpr/hpr/bin/hpr
PIDFILE=/var/run/$BASE.pid
LOGFILE=/var/log/$BASE.log
OPTS=
DESC="Helium Packet-Router"

# Get Linux Standard Base functions
. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
    . /etc/default/$BASE
fi

# Check if executable is present
if [ ! -x $DAEMON ]; then
    log_failure_msg "$DAEMON not present or not executable"
    exit 1
fi

case "$1" in
    start)
        touch "$LOGFILE"
        chgrp helium "$LOGFILE"

        ulimit -n 1048576

        if [ "$BASH" ]; then
            ulimit -u unlimited
        else
            ulimit -p unlimited
        fi

        log_begin_msg "Starting $DESC: $BASE"
        start_daemon -p "$PIDFILE" "$DAEMON"
        log_end_msg $?
        ;;
    stop)
        log_begin_msg "Stopping $DESC: $BASE"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
        ;;
    kill)
        log_begin_msg "Sending SIGKILL to $DESC: $BASE"
        kill -SIGKILL $(cat $PIDFILE)
        log_end_msg $?
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
	status_of_proc -p "$PIDFILE" "$DAEMON" "$DESC"
        ;;
    *)
        echo "Usage: service $BASE {start|stop|restart|status}"
        exit 1
        ;;
esac
