name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  compute-base-build-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.out.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Create Tag
        id: out
        run: echo "tag=${{ hashFiles('Dockerfile') }}" >> "$GITHUB_OUTPUT"

  build-base:
    needs: compute-base-build-tag
    runs-on: ubuntu-latest
    env:
      CACHE_HIT: false
      IMAGE: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Cached base Image
        run: |
          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "CACHE_HIT=true" >> $GITHUB_ENV
          else
            echo "CACHE_HIT=false" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        if: env.CACHE_HIT == 'false'
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: Build and Push base Image (if not cached)
        if: env.CACHE_HIT == 'false'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: Dockerfile
          target: base
          push: true
          tags: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}

  build:
    runs-on: ubuntu-latest
    needs: [compute-base-build-tag, build-base]
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Cache _build Directory
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: build
        run: make
      - name: build test
        run: ./rebar3 as test compile

  xref:
    needs: [compute-base-build-tag, build-base, build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-xref
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: xref
        run: ./rebar3 xref

  eunit:
    needs: [compute-base-build-tag, build-base, build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-eunit
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: eunit
        run: ./rebar3 eunit -v

  dialyzer:
    needs: [compute-base-build-tag, build-base, build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-dialyzer
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: dialyzer
        run: ./rebar3 dialyzer

  suites:
    runs-on: ubuntu-latest
    outputs:
      ct_suites: ${{ steps.gen_test_suites.outputs.ct_suites }}
      aws_suites: ${{ steps.gen_test_suites.outputs.aws_suites }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: gen_test_suites
        id: gen_test_suites
        run: |
          CT_SUITES="["
          AWS_SUITES="["
          for F in ./test/*_SUITE.erl; do
            SUITE=$(basename "$F")
            if [ "$SUITE" = "hpr_packet_reporter_SUITE.erl" ]; then
              AWS_SUITES+="\"${SUITE}\","
            else
              CT_SUITES+="\"${SUITE}\","
            fi
          done
          CT_SUITES=${CT_SUITES%,}
          CT_SUITES+="]"
          AWS_SUITES=${AWS_SUITES%,}
          AWS_SUITES+="]"
          echo "ct_suites=${CT_SUITES}" >> "$GITHUB_OUTPUT"
          echo "aws_suites=${AWS_SUITES}" >> "$GITHUB_OUTPUT"

  ct:
    needs: [compute-base-build-tag, build-base, build, suites]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    strategy:
      fail-fast: false
      matrix:
        suite: "${{ fromJSON(needs.suites.outputs.ct_suites) }}"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ct-${{ matrix.suite }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: ct
        run: CT_LAGER=DEBUG ./rebar3 ct --suite=${{ matrix.suite }} --readable=true

  ct-aws:
    needs: [compute-base-build-tag, build-base, build, suites]
    if: ${{ needs.suites.outputs.aws_suites != '[]' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    strategy:
      fail-fast: false
      matrix:
        suite: "${{ fromJSON(needs.suites.outputs.aws_suites) }}"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ct-aws-${{ matrix.suite }}
      cancel-in-progress: true
    services:
      localstack:
        image: localstack/localstack:1.4
        env:
          SERVICES: s3
        ports:
          - "4566-4583:4566-4583"
        volumes:
          - "/var/lib/localstack:/var/lib/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      HPR_PACKET_REPORTER_LOCAL_HOST: ${{ secrets.HPR_PACKET_REPORTER_LOCAL_HOST }}
      HPR_PACKET_REPORTER_LOCAL_PORT: ${{ secrets.HPR_PACKET_REPORTER_LOCAL_PORT }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install AWS CLI
        run: apk add --no-cache aws-cli
      - name: Localstack init
        timeout-minutes: 1
        run: |
          until curl -sf http://localstack:4566/health > /dev/null 2>&1; do
            echo "...waiting for Localstack..."
            sleep 2
          done
          aws configure set aws_access_key_id testkey
          aws configure set aws_secret_access_key testsecret
          aws configure set default.region us-east-1
          aws --endpoint-url=http://localstack:4566 s3 mb s3://test-bucket
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: ct
        run: CT_LAGER=DEBUG ./rebar3 ct --suite=${{ matrix.suite }} --readable=true

  release:
    needs: [compute-base-build-tag, build-base, build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/base:${{ needs.compute-base-build-tag.outputs.image_tag }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            _build
            src/grpc/autogen
          key: build_cache-${{ hashFiles('rebar.config','rebar.lock') }}
          restore-keys: |
            build_cache-
      - name: release
        run: make rel

  package:
    needs: [xref, eunit, dialyzer, ct, ct-aws, release]
    if: ${{ !failure() && !cancelled() && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3-slim
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-package
      cancel-in-progress: true
    steps:
      - name: deps
        run: |
          apt update &&
          apt install --yes autoconf automake bison gcc libc6-dev binutils libbz2-dev curl libdbus-1-dev flex git libgmp10 libgmp-dev libsodium-dev libtool liblz4-dev libssl1.1 libssl-dev pkgconf bash protobuf-compiler sed tar wget vim zip ruby
      - name: install cmake
        uses: lukka/get-cmake@v3.31.4
      - name: fpm install
        run: gem install fpm
      - name: rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # stable
        with:
          toolchain: stable
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: build and package
        run: ./.github/scripts/make_deb.sh
      - name: packagecloud upload
        env:
          PACKAGECLOUD_API_KEY: ${{ secrets.PACKAGECLOUD_API_KEY }}
        run: ./.github/scripts/packagecloud_upload.sh
