name: packaging

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3-slim

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: deps
        run: |
          apt update &&
          apt install --yes autoconf automake bison gcc libc6-dev binutils libbz2-dev curl libdbus-1-dev flex git libgmp10 libgmp-dev libsodium-dev libtool liblz4-dev libssl1.1 libssl-dev pkgconf bash protobuf-compiler sed tar wget vim zip ruby

      - name: install cmake
        uses: lukka/get-cmake@v3.31.4

      - name: fpm install
        run: gem install fpm

      - name: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/checkout@v2

      - name: build and package
        run: |
          ./.github/scripts/make_deb.sh

      - name: packagecloud upload
        env:
          PACKAGECLOUD_API_KEY: ${{ secrets.PACKAGECLOUD_API_KEY }}
        run: |
          ./.github/scripts/packagecloud_upload.sh
